### ISSUE TITLE
Chat input form not visible/ availible under iPadOS

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#101]
**Describe the bug**
When Using the IOS-Webbrowser the form `chatForm` is not visible/availible

**To Reproduce**
1. Open A stream using the chat-feature under iPadOS
2. Don't see chat

**Expected behavior**
The chat should be visible.

**Screenshots**
IOS:
![IMG_0457](https://user-images.githubusercontent.com/26258709/125442162-2ff02857-40a6-47e7-8735-5c51f38ffaa2.jpg)

Chrome-Desktop:
![Screenshot_20210713_130848](https://user-images.githubusercontent.com/26258709/125441911-72381d68-5a96-4d81-994b-4f4355e1e1d3.png)

**Desktop:**
 - OS: Linux
 - Browser Chrome
 - Version 91.0.4472.114

**Smartphone:**
 - Device: iPad Pro
 - OS: iPadOS 14.6
 - Browser safari
 - Version 14

**Additional context**
It does not seem to be the case of bad scaling, as scaling the desktop does not result in the `chatFrom` not showning..

**Comment by joschahenningsen** [comment]
Thank you! Let's see if I can figure this issue out without an iPad. 
Once people start actually using the chat it needs a redesign anyways though, especially in terms of mobile (tablet) optimisation... :smile:

**Comment by joschahenningsen** [comment]
Got an iPad and found the issue: It seems like the apple webkit treats css like `height:100vh` in a weird way. The top navigation bar is included in the calculation of the viewport height. Funnily enough, even google is struggling with this: 

https://user-images.githubusercontent.com/44805696/129459006-dda1cd79-6f73-4582-9b9b-f68738db79d1.MP4

Context: https://bugs.chromium.org/p/chromium/issues/detail?id=720048

As some courses will use the chat next semester, instead of hacking around this I’ll redesign the watch page and chat very soon :)
