### ISSUE TITLE
Not possible to view live streams, because there is not a link attached.

### ISSUE THREAD

**Issue by ZeynepOzturk66** [joschahenningsen/TUM-Live#1241]

**Comment by ZeynepOzturk66** [comment]
Live function doesnt work. 
I wrote: https://live.rbg.tum.de and loged in. Than I tried to click the Link to my live lecture (and because this didn't work, I also tried other lectures). I now could see all of the previous lectures, but not the live one. 
<img width="1152" alt="Bildschirmfoto 2023-11-20 um 14 02 26" src="https://github.com/TUM-Dev/gocast/assets/132444902/3b0397fb-8b9d-4d53-aa3f-9b55db1ff0c7">
When I got back to my home page, I can click to one where it
<img width="1083" alt="Bildschirmfoto 2023-11-20 um 14 03 19" src="https://github.com/TUM-Dev/gocast/assets/132444902/e706543b-1113-47c6-b159-5cdea7001d0d">
 works.:
Naive Baits is the only one where I can click and I get to the live lecture.

**Comment by YiranDuan721** [comment]
Moin Zeynep,
in order for this issue to be more accurately understood, I've edited the title and deleted the content of the first comment (which was just a bug report template), I hope this won't cause you too many problems.

Could you please provide the following information, so that further examinations and debugging can be carried out:
1. The operating system you were using when the problem occurred
2. The browser you were using when the problem occurred
3. If it's convenient: The version of the operating system, and the browser

Thank you!

**Comment by SebiWrn** [comment]
As there is no more information on this issue provided I will close it. Please reopen it if the bug still exists.
