### ISSUE TITLE
UX: Longer sessions

### ISSUE THREAD

**Issue by alexmo1997** [joschahenningsen/TUM-Live#1302]
**Is your feature request related to a problem? Please describe.**
Currently, when I logon to TUMLive, those sessions expire after a week.
On Desktop, this isn't a big of a deal, but on mobile it is really frustrating that I have to relogin every week.

**Describe the solution you'd like**
Make sessions (much) longer in general (or not expire at all) and/or refresh them when the user uses the site. 
I know of no other streaming sites where I have ever had the problem of being logged out.
Frankly, I don't think an applications such as TUMLive warrants such special security measures.

**Describe alternatives you've considered**
- Only make sessions longer for students (so admins/lecturers don't lose any security benefits)
- Make it a setting
- Make them longer only for mobile useragents
- Have a TUMLive app (but I guess inside of that app you would still have persistent sessions, so why not do that for the website)

**Additional context**
I am not sure if there is something you can do about this given that this is probably mostly handled by Shibboleth, but I hope so.

**Comment by YiranDuan721** [comment]
I am considering to add a "Remember me" option on the login page, and set the cookie to be valid for 6 months if it is selected. Do you think 6 months is a good idea? I'd like to hear from anyone.

**Comment by YiranDuan721** [comment]
This (realising a "remember-me" feature with jwt) turns out to be a more complex thing than I originally thought.

A simple solution would be similar to what I did last week (#1310). This is also how it is implemented in [Artemis](https://github.com/ls1intum/Artemis/blob/df2a5a9a9abf252ed203aa6e93d53df3b25b22dd/src/main/java/de/tum/in/www1/artemis/security/jwt/TokenProvider.java). Artemis currently adopts 3-days as the token validity when "remember-me" is not checked at log-in, and 1-month as when checked.

A more recommended way is, according to [this answer](https://stackoverflow.com/a/26834685), and [as Joscha suggested](https://github.com/TUM-Dev/gocast/pull/1310#issuecomment-1891020297), to refresh the token before it expires every time the user opens the website.

I will try to implement the second way today, but not sure whether this would go smoothly; if not, I don't think I still have time to work on it until 1st March. Wish me luck =w= And I appreciate any comments and suggestions.

**Comment by SebiWrn** [comment]
This feature is not planned as it would induce a security issue due to long sessions.

**Comment by alexmo1997** [comment]
I don't mean that in a bad way, but could you explain how this is a security issue? I really am curious, as I never have had to relogin to YouTube, Twitter, GitHub or any popular website for that matter.
