### ISSUE TITLE
displaying slide numbers as bookmarks 

### ISSUE THREAD

**Issue by 0Daeden4** [joschahenningsen/TUM-Live#1327]
**Is your feature request related to a problem? Please describe.**
Since there is a large amount of students who prefer studying using the slides used in the lectures opposed to watching the whole lecture, I think it would be a good addition to be able to see the timestamps of slides as if they were bookmarks. This addition would both make finding the lecture you want as well as jumping to a specific section you have not understood easier and faster, hence save a lot of time. 

**Describe the solution you'd like**
Being able to see which slides were covered in which lecture would be a great addition and could be displayed as (s130-140) near the date of the lecture. Additionally being able to see when a slide has been discussed, in the form of bookmarks would be a great addition in relation to the reasons I stated above. I don't know how this would be technically achievable since auto detecting the slide numbers might be difficult or not efficient in some cases but I always had the feeling that since the position where the slide numbers are displayed rarely changes, I thought maybe scanning the small portion of the screen where these numbers are displayed would be doable. But this observation is only limited to the lectures I attend and not other and I also don't know how this could work :)

**Describe alternatives you've considered**
Excessive use of bookmarks.

**Additional context**

**Comment by SebiWrn** [comment]
I'm sorry but I don't think this is really possible because every slide deck is different and the numbers are on different places. In addition to that some lecturers have one slide deck for the whole semester and some have one for every single lecture.

If you want notes like that on your lectures, please tell your lecturer to add these in the description of the videos. This can easily be done in the admin panel.
