### ISSUE TITLE
Stream end causes page refresh, interrupting dvr viewers

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#189]
**Describe the bug**
When a stream ends, the websites reloads and the "no active stream" placeholder is shown. This leads to interruption for viewers that are behind the live edge or streams via OBS where the last few seconds might be cut off (due to the latency between the streamer ending the broadcast and the viewers watching it.)

**Expected behavior**
There should be a tiny red info text somewhere close to the stream when it ends instead of a page refresh. (e.g. `broadcast ended`)

**Comment by joschahenningsen** [comment]
https://github.com/joschahenningsen/TUM-Live/blob/7944cb492a0c11df54a34ed518ccf795a5a7dd45/web/ts/watch.ts#L34 

This should only happen when the stream starts, not when it ends

**Comment by joschahenningsen** [comment]
@mono424 something for you maybe? I think it would help if I got streaming to work on the testserver first though :D

**Comment by mono424** [comment]
Nice I will take that task! :)

**Comment by LadnerJonas** [comment]
Especially when using the beta, non-live viewer of a livestream, this issue is quite annoying as a user/student. For example, let's take an "Einführung in die Informatik" student, which happens to be 10 min behind the livestream. When the lecturer stops the stream, or the time limit is exceeded, the students' browser window gets refreshed/the stream stops. Because of that, the student has to wait until the VOD is processed and then can continue to watch the last 10 min of a lecture.
