### ISSUE TITLE
Automatically trim recordings

### ISSUE THREAD

**Issue by boi4** [joschahenningsen/TUM-Live#423]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I watch a recorded lecture and need to skip multiple minutes of silence/lecture setup to the actual beginning.

**Describe the solution you'd like**
Hello everyone,

I'm a big fan of the new streaming site and use it for many of my lectures.
One thing that I've noticed is that most recordings seem to be turned on and off automatically which leads to big sections of silence at the beginning and end of the recorded lectures.

I think it should be possible to auto detect these sections and remove them using [ffmpeg](https://ffmpeg.org/ffmpeg-filters.html#silencedetect).

Maybe both the full and trimmed version could be hosted by the site and switched somehow.

What do you think?

**Describe alternatives you've considered**
Downloading the videos and doing it myself locally on my computer :wink:

**Comment by joschahenningsen** [comment]
> I'm a big fan of the new streaming site and use it for many of my lectures.

Yay! :partying_face: :heart: 

What we currently do is automatically detect silences in recordings and offer a button to skip them (for example here: https://live.rbg.tum.de/w/FDS/12051)

I didn't start automatically cutting recordings yet because I'm not confident about false positives (e.g. here: https://live.rbg.tum.de/w/ccppprog/15036 we detected silences where there are none) 
Addtitionally, some lectures overlap with other lectures, so the video doesn't start with silence but with some other lecture instead... If you have any ideas on how to enhance the feature, feel free to share them :)

**Comment by boi4** [comment]
Oh, then it's my bad, I didn't see that the feature is already implemented!
Great Job! :) I'm gonna close the issue, because the current apporach fixes the problem.
