### ISSUE TITLE
Add keyboard controls 

### ISSUE THREAD

**Issue by Raupinger** [joschahenningsen/TUM-Live#43]
Being able do do things like play/pause by pressing the space bar would be nice.

**Comment by Trattue** [comment]
At least on Firefox, a temporary user-side "fix" for this is to display the browser's media controls by right-clicking the video

**Comment by joschahenningsen** [comment]
There is a plugin for videojs that provides shortcuts: https://github.com/ctd1500/videojs-hotkeys. I'd like to avoid it because it would be rather large (also it doesn't seem to be maintained very frequently) but if I don't find the time to implement shortcuts myself before the semester starts, I'll temporarily use it.
