### ISSUE TITLE
npm install doesn't work on version >= 16

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#515]
**Describe the bug**
Can't run `npm install` for `node --version` >= 16 on MacOS and potentially other operating systems after #479.

**To Reproduce**
1. `cd web/`
2. `rm -rf node_modules/`
3. `npm install`

**Expected behavior**
success 

**Got: Error**
https://pastebin.com/Qs7Km4Dj

**Current work-around**
Can be fixed by either upgrading `videojs-hls-quality-selector` to a current version, or downgrading `node` to version < 16. 

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
 - Browser: -
 - Version: Version 12.4

**Additional context**
If this isn't a problem on other operating systems, this could potentially be a _wontfix_.

**Comment by alexanderstephan** [comment]
Hm, that is pretty annoying. I could also reproduce this on my mac. I think we should just revert it to the latest version. The warning is not harmful and I hope they at least update the plugin when the deprecated API is removed from vjs.

Otherwise, I am pretty confused why pulling packages from git suddenly causes such problems. I had no success with debugging. I feel like this caused by an outdated `node-gyp` in the plugin.

If I look at the dependencies, I wonder if we should use the plugin at all... 😅

<img width="1666" alt="grafik" src="https://user-images.githubusercontent.com/30267166/172075647-ee14f697-be48-4070-93ed-75163590764f.png">
