### ISSUE TITLE
Document keyboard shortcuts

### ISSUE THREAD

**Issue by lukaskollmer** [joschahenningsen/TUM-Live#530]
**Is your feature request related to a problem? Please describe.**
Just lost my position in a lecture recording as a result of using the cmd+1 keyboard shortcut (i'm on a mac, so i guess the linux/windows equivalents would be different).
The shortcuts `cmd+n` (with $n \in \\{1, 2, ..., 8\\}$) in Chrome will usually switch to the n-th tab from the left, but it seems like the video player overrides these commands to jump to different sections of a video. However, this is not documented anywhere.

**Describe the solution you'd like**
Document the keyboard commands.
Many web-based applications (such as e.g. Gmail or GitHub) are using the shift+? keyboard shortcut to present an overlay/menu listing all possible keyboard shortcuts, so this might be a good thing to do as well.
Documenting the commands would:
- make it clearer what they do exactly (i'm still not sure what exactly the overwritten cmd+n commands do. do they always jump in 14-minute intervals, or do they jump to 1/10-of-the-whole-video timestamps?)
- make the commands more discoverable. (after realising that the cmd+n commands exist i continued to press some random buttons, and it seems like `j`, `k`, `l`, `m`, `z`, and `x` also are mapped to certain actions, but then again it is impossible to easily know what they do exactly, without delving into the source code of the website)

**Describe alternatives you've considered**
- Just not do anything and leave it as-is
- Add a section listing all available keyboard shortcuts somewhere else (e.g. in the settings page)
- Have some kind of questionmark-button at the bottom right of the video player, next to the camera mode and feedback buttons

**Comment by just-max** [comment]
Yeah, good point with both documentation and the player stealing the `alt+n`/`cmd+n` shortcuts!

About the documentation: basically, these are 1:1 YouTube's shortcuts where those made sense in TUM-Live (see #476 and [YouTube docs](https://support.google.com/youtube/answer/7631406?hl=en)). I think I could add something to document them, probably building on #489. I wasn't aware how many sites had keyboard shortcuts until I tried `shift+?` on them :)

The issue with stolen shortcuts should be easy to fix by checking that the [alt modifier](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/altKey) is not pressed. Probably checking the control key makes sense too, but not shift, otherwise shortcuts that require shift won't work anymore :( I'm not aware how to solve this issue in full generality so that shortcuts are never stolen.

**Comment by CommanderStorm** [comment]
@just-max  Is this issue solved by #587?
If not why did you not mark this as a resolving PR?

**Comment by just-max** [comment]
To anyone reading this issue: the bug of stealing shortcuts is resolved in #587 but the enhancement of documenting shortcuts is not. Therefore the issue remains open for now.
