### ISSUE TITLE
Volume control keys shouldn't change stream player volume

### ISSUE THREAD

**Issue by JeremiasBohn** [joschahenningsen/TUM-Live#545]
**Describe the bug**
Using media keys to control the volume changes the stream player's volume. This doesn't make sense as I already modify my system volume.

**To Reproduce**
1. Open any livestream
2. Use your keyboard's media keys for volume up or volume down

**Expected behavior**
The media player's internal volume stays the same, the system's volume changes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 102.0.5005.115

**Additional context**

**Comment by just-max** [comment]
Fair point, wasn't quite sure what to do with these keys because on my system the always control the system volume (even on TUMLive). Just to confirm, the behaviour on TUMLive is different from what e.g. YouTube does?

I'm not sure about the rest of the media keys, in particular we currently also handle the play/pause media keys and play speed media keys. Handling these should probably also be removed, thoughts?

Here is the relevant code
https://github.com/joschahenningsen/TUM-Live/blob/3bfd69600145d41447ff37abcec0a4839a7d915b/web/ts/hotkeys.ts#L114
