### ISSUE TITLE
Adjust video player size for medium wide viewport

### ISSUE THREAD

**Issue by LeonStaufer** [joschahenningsen/TUM-Live#58]
On medium-wide viewports, the video player is scaled to 2/3 of the width. As it is already set to 100% for very small screens, I believe it would be nice, to make the same adjustment for medium-sized screens.

I think that only the following line might need to be updated.
https://github.com/joschahenningsen/TUM-Live/blob/2657548eaca8ebcbfcf497e8dd1a1a5e95dcd376/web/template/watch.gohtml#L18

**Comment by joschahenningsen** [comment]
Nice observation, I didn't go for full width on md sized screens because I wanted people to be able to chat there as well [1].
When the chat is disabled, full width definitely makes sense! 

1):
![image](https://user-images.githubusercontent.com/44805696/115015694-5a3a3c80-9eb4-11eb-8a2e-43acce9e764e.png)

**Comment by joschahenningsen** [comment]
Should look a little better now. LMK if there's anything you would still adjust :)

**Comment by LeonStaufer** [comment]
Thanks :)
