### ISSUE TITLE
Start page redesign

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#597]
**Is your feature request related to a problem? Please describe.**
The start page lags a bit behind in terms of styling. I like that it is so minimal, but it could be a bit more visually grouped and better fit in with the other design reworks (e.g. use of containers with small borders, different font styles, ...)

**Describe the solution you'd like**
As this is a rather important rework, we can collect ideas here. After all it is the thing that the people see when they first visit the site, so want to make a good impression. :D 

It would be also cool rework the hiding of courses since it is a bit unconsistent. Maybe it can be done similar to pinning courses.

**Comment by ata-keskin** [comment]
I think we can have a dropdown menu on the lower left corner of the screen that appears when the user has hidden courses. It can contains the names of the hidden courses, instead of the restore links that appear at the bottom of the course list. The dropdown menu should be as minimal as possible and scrollable when opened, (similar to the semester selector). Also the inner mechanism can also be made same as the one for pinning courses (which should be really easy to do)

**Comment by just-max** [comment]
I had some time and put together a prototype, see #610. I'd appreciate feedback/suggestions!
