### ISSUE TITLE
Beta Stream: Change playback speed to 1.0x when the live content is reached

### ISSUE THREAD

**Issue by LadnerJonas** [joschahenningsen/TUM-Live#667]
**Is your feature request related to a problem? Please describe.**
Beta Stream feature: I'm always frustrated when I start a lecture 30 min late, then set the playback speed to > 1.0 (e.g.) to catch up with the live stream. After some time, the 30-min buffer to the live stream is watched and the client tries to stream the live content with a play speed > 1.0. Because of this, every few seconds the client has to buffer (because the is no newer content than live) and then continues the playback with a speed > 1.0.

**Describe the solution you'd like**
When reaching the live stream and the client has to buffer to get new content, reduce the playback speed to 1.0. Then the live stream can be watched without any hiccups.

**Describe alternatives you've considered**
Maybe a small notification could inform the user about the too high playback speed for the live stream. But this is not really a great solution.

**Additional context**
Beta Stream of any active live stream

**Comment by xarantolus** [comment]
I'm interested in implementing this change.
I played around with the video.js configuration that is used and I think I have something that might work, but would like to test that on a livestream. I've set up everything locally (mariadb in docker, tum-live locally and the worker in docker) - the stream configuration gives me `rtmp://ingest.tum.live/stream?secret=...` as stream server in OBS, but that doesn't seem to work at all. I also tried `rtmp://localhost:8081/stream?secret=...` and port 8060 and 1935, but none seem to work. Maybe I misunderstand the self-streaming part

**Comment by joschahenningsen** [comment]
> I'm interested in implementing this change.

That's great, thanks a ton! 
I'm afraid live streaming locally is quite a challenge because we still depend on a few services provided by the LRZ which are not usable locally without secrets(passwords, etc.). For now I'd suggest using a livestream from our site that's allready running by copying the url (button below the video) and pasting it into the database (`streams`.`playlist_url`) yourself. I suggest using datagrip, LMK if you have any further questions :)
