### ISSUE TITLE
My internet is quite slow, and it is constantly interrupting the video please make it possible to change resulution to lessen the load on my connection

### ISSUE THREAD

**Issue by Zuced** [joschahenningsen/TUM-Live#727]
**Is your feature request related to a problem? Please describe.**
Slow connection results in interrupting video

**Describe the solution you'd like**
make resolution change possible, to lessen the load on my connection

**Describe alternatives you've considered**
maybe higher bufferamounts to bridge the interrupts

**Comment by CommanderStorm** [comment]
Hi Zuced,
You can ask your lecturer, if making downloads available would be possible, as it is nessesary for you watching their recordings.
Downloads are a better fit for your use case, imo since they can better cope with very limited connections.

(If they don't, here is a more technical project which solves your use case: https://github.com/Valentin-Metz/tum_video_scraper)
