### ISSUE TITLE
Send private replies in moderated chat.

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#781]
**Is your feature request related to a problem? Please describe.**
Tweedback offers the functionality to not approve a message, but still reply to it. This way a question that should not be public can still be answered.

**Describe the solution you'd like**
If a message is not or approved or even declined, moderators still can reply. The person that posted the original message is also able to see the reply besides the moderators. Other people should not notice anything.

**Comment by MatthiasReumann** [comment]
From what I can tell, this should already be possible. 🧐 
As long as you don't delete the message replies (public or private) should be possible - or am I missing something?

**Comment by Jojaa350** [comment]
This issue refers to the versions of TUM-Live before #779, where the reply-button was only shown if the message was set as visible (see here: https://github.com/joschahenningsen/TUM-Live/pull/779/files#diff-5959a8c25a9b5eac7fa075a66ea46147192040a4e63ef71909f57b7696840ef2L62)

~~I am however curious: I cannot try that myself but looking at the code it doesn't appear like the author can reply to his own hidden message, as stated in the description. I can image situations where a student might want to respond to a private reply of an admin.~~
Nevermind, I'm just stupid. Yep, apparently this issue is already resolved.

**Comment by MatthiasReumann** [comment]
Ah, that makes sense. 😅 So we can close this issue right?

**Comment by Jojaa350** [comment]
I guess so, yes.
